# Generated by Django 5.0.1 on 2024-02-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wishlist',
            new_name='watchlist',
        ),
    ]
