# Generated by Django 5.0.1 on 2024-02-01 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_wishlist_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings_made',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='made_by', to='auctions.auctionlisting'), # type: ignore
            preserve_default=False,
        ),
    ] # type: ignore
