# Generated by Django 5.0.1 on 2024-02-03 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_listings_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='listings_made',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_by', to='auctions.auctionlisting'),
        ),
    ]
