# Generated by Django 5.0.1 on 2024-02-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlisting_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='state',
            field=models.CharField(choices=[('W', 'Winning'), ('O', 'Outbid'), ('L', 'Lost'), ('F', 'Final')], default='W', max_length=1),
        ),
    ]
