# Generated by Django 5.0.1 on 2024-02-04 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='auctions.auctionlisting'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
