# Generated by Django 5.0.1 on 2024-02-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
