# Generated by Django 5.0.1 on 2024-02-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='earliest_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
